### PR TITLE
Add support for epd7in3e

### PR DESCRIPTION
**Pull request by antoinecellerier**
- **Switch back to upstream waveshareteam/e-Paper repo**
- **Add support for waveshare_epd.epd7in3e**
Proper color display is dependent on waveshareteam/e-Paper#363 being merged

### CODE REVIEW

**Comment by robweber** [comment]
Thanks for contributing. Couple of questions: 

1. Have you tried the upstream waveshare repo in any long term capacity? Been a while since I've tried but there was a pretty critical error for most b/w EPDs where it would error out when trying to wake from sleep. I'll pull this and test on my own but just curious. 
2. Is your 7in3e implementation dependent on the upstream merge? At first glance I'm thinking no since the method calls are the same but unsure how the changed code affects actual use.

**Comment by antoinecellerier** [comment]
I've not had the opportunity to test the upstream repo with other EPDs recently no. I only have the 7in5b and 7in3e displays so no opportunity to really test black and white :-/
The upstream merge isn't technically required for things to work, it just fixes the colors being all shuffled. e.g. blue shows up as red without the fix.

**Comment by robweber** [comment]
Currently running this with SlowMovie to ensure the previous Waveshare repo error is ironed out. So far so good. I'll let it run through the weekend. Usually I can run for months without issues, most of a week should be a good test. Otherwise it all looks good.

**Comment by antoinecellerier** [comment]
thanks

**Comment by antoinecellerier** [comment]
Looks like the color issue I had referenced on the waveshare repo got fixed 5 days ago without needing to merge the PR I'd shared. I've not verified it works yet but likely good news.

**Comment by robweber** [comment]
Been running this for a while without any major issues. Had one lock-up but I think that may have been related to the video file. In the past (when the bug was present) things failed within the first 30-60 minutes.

**Pull request merged**
