### PR TITLE
Fix epd5in83c in WaveshareTriColorDisplay

### PR DESCRIPTION
**Pull request by dr-boehmerie**
Use driver name instead of device name in `super().__init__()`

### CODE REVIEW

**Comment by robweber** [comment]
Thanks for taking a look at this. Do you have one of these displays and can confirm this is working?

**Comment by dr-boehmerie** [comment]
Yes, I do have the black/yellow version of the 5in83 display, and just started to play around a bit with it and https://github.com/TomWhitwell/SlowMovie. Works for me, as well as just displaying an image using the basic example in omni-epd.  Can't check if the fix breaks one of the other TriColor waveshare displays handled by the same class, though. But I would mark this one as supported in the README.md 👍 

Will try out the 2in9 e-Paper module and the 2in7 e-Paper HAT later.

**Comment by dr-boehmerie** [comment]
The 2in9 e-Paper module (waveshare_epd.epd2in9) is a bw only display, the color mode info in the table seems wrong. It works out of the box, in bw mode, and the 2in7 e-Paper HAT (waveshare_epd.epd2in7) as well. I will update the table accordingly.

**Comment by robweber** [comment]
Thanks for testing these. The 2.9in must have just been a documentation error. I checked the places in the code where that driver is loaded and the normal 2.9 and 2.9v2 are only used as BW whereas the B and C models use the TriColor class.

**Pull request merged**
