### PR TITLE
Waveshare 4-color displays

### PR DESCRIPTION
**Pull request by missionfloyd**
This will add support for Waveshare's new black/white/yellow/red displays.

https://www.waveshare.com/1.64inch-e-paper-module-g.htm
https://www.waveshare.com/3inch-e-paper-module-g.htm
https://www.waveshare.com/7.3inch-e-paper-hat-g.htm

I have a 3-inch on the way to make sure this works.

### CODE REVIEW

**Comment by robweber** [comment]
Awesome!

**Comment by missionfloyd** [comment]
It works.

IMG_0906

**Comment by robweber** [comment]
This is looking pretty good to me, thanks for putting it all together. Tempted to buy one of these myself now. Unless you have any additional tweaks to make I'll merge it in.

**Comment by missionfloyd** [comment]
I think it's good to go.

**Pull request merged**
