### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by aaronr8684**
Fixed typo in deviceList and super function call

### CODE REVIEW

**Comment by aaronr8684** [comment]
This was tested locally after making the changes and reinstalling via pip

**Comment by robweber** [comment]
Thanks for fixing this. You were able to test this on the 5.65in display?

**Comment by aaronr8684** [comment]
Yes, sorry. I should have been more explicit. That was the screen I tested with on my local device. I'm also having issues with the 7.5" bw/red screen, but I want to test it more before opening an issue or PR. I also have yet to test my 3.7". They're all waveshare screens

**Comment by robweber** [comment]
That's great, thanks. I'll mark that screen as tested in the README as well then. The 3.7 I've personally tested but if you can do others, or find issues let me know. Thanks for the contribution.

**Pull request merged**
